<?php

/**
 * @file
 * Generate a PDF for the print_pdf module using the mPDF library.
 *
 * @ingroup print
 */

/**
 * Implements hook_pdf_tool_info().
 */
function print_pdf_mpdf_pdf_tool_info() {
  $info = array(
    'name' => 'mPDF',
    'min_version' => '7.1.0',
    'url' => 'https://github.com/mpdf/mpdf/releases/latest',
    'expand_css' => FALSE,
    'public_dirs' => array(
      'ttfontdata',
      'tmp',
    ),
  );

  $pdf_tool = explode('|', config_get('print_pdf.settings', 'print_pdf_pdf_tool'));
  // Only for versions less than 7.0.0, without calling the version() function.
  if (isset($pdf_tool[1]) && strpos($pdf_tool[1], 'mpdf.php')) {
    $info['tool_dirs'] = array(
      'graph_cache',
    );
  }
  return $info;
}

/**
 * Implements hook_pdf_tool_version().
 */
function print_pdf_mpdf_pdf_tool_version($pdf_tool) {
  $version = 'unknown';

  // Version 7 of the mpdf library uses a composer autoloader.
  // Also there no longer is way to truly detect the library version, so this
  // seems like the best alternative.
  // Assuming it is installed via composer inside a directory that Print
  // module scans. Print will always check ./libraries.
  $autoload_path = dirname($pdf_tool) . '/../../../autoload.php';
  $composer_path = dirname($pdf_tool) . '/../../../composer';

  if (file_exists($autoload_path) || (module_exists('xautoload') && is_dir($composer_path))) {
    if (module_exists('xautoload') && is_dir($composer_path)) {
      xautoload()->adapter->composerDir($composer_path);
    } elseif (file_exists($autoload_path)) {
      require_once $autoload_path;
    }

    if (class_exists('\Mpdf\Mpdf')) {
      $version = \Mpdf\Mpdf::VERSION;
    }
  } elseif (file_exists(BACKDROP_ROOT . '/' . $pdf_tool)) {
    include_once BACKDROP_ROOT . '/' . $pdf_tool;
    if (defined('mPDF_VERSION')) {
      $version = mPDF_VERSION;
    }
  }

  return $version;
}

/**
 * Implements hook_print_pdf_available_libs_alter().
 */
function print_pdf_mpdf_print_pdf_available_libs_alter(&$pdf_tools) {
  module_load_include('inc', 'print', 'includes/print');
  $tools = _print_scan_libs('mpdf', '!^(mpdf.php|Mpdf.php)$!');

  foreach ($tools as $tool) {
    $pdf_tools['print_pdf_mpdf|' . $tool] = 'mPDF (' . dirname($tool) . ')';
  }

  // mPDF >= 7.0 uses a composer autoloader.
  $tools = _print_scan_libs('mpdf', '!^autoload.php$!');
  foreach ($tools as $tool) {
    if (preg_match('!mpdf.*?/vendor/autoload.php$!', $tool)) {
      $pdf_tools['print_pdf_mpdf|' . $tool] = 'mPDF (' . dirname(dirname($tool)) . ')';
    }
  }
}
